package upl.compiler;

enum TokenType {
	AND, AS, ASSIGN, BOOL, COLON, COMMA, DIV, DO, EOF, ELSE, EQ, EXPONENT, FALSE, FLOAT, FUNC, GE, GLOBAL, GT, ID, IF, INT, INTDIV, LAMBDA,
	LBRACE, LBRACK, LE, LOAD, LIST, LPAR, LT, MINUS, MOD, NE, NONE, NOT, NUM, OR, PERIOD, PLUS, PRINT, PROMPT, QUOTE, RANDOM, RBRACE,
	RBRACK, RPAR, SEMICOLON, STAR, STR, STRING, TIMES, TYPEOF, TRUE, WHILE
}
